### ISSUE TITLE
tempfile.mkdtemp() causing "No space left on device error"

### ISSUE THREAD

**Issue by jmodlis** [crowelab/PyIR#5]
Hi,

I am trying to run PyIR on many files simultaneously. It is a great wrapper for IgBlast and I have been able to parse the json files easily.  But, I am running into a space issue with the tmpdir. 

Line 26 of factory.py contains this command:
```args['tmp_dir'] = tempfile.mkdtemp()```

Which appears to be root cause of the "No space left on device" error that I am seeing below.  Some of the jobs work but most fail.  I am running this job on a cluster.

My current workaround will be to set the environment variable TMPDIR to a directory with sufficient space, but this may be an issue that others may run into as well. 

Error output:
```Traceback (most recent call last):
  File "/data/omicscore/Easterhoff-Easterhoff-20190501/scripts/PyIR/bin/./pyir", line 14, in <module>
    py_ir.run()
  File "/data/omicscore/Easterhoff-Easterhoff-20190501/scripts/conda/envs/py36/lib/python3.6/site-packages/pyir/factory.py", line 53, in run
    total_seqs, input_pieces, fastq_input_pieces = self.split_input_file(input_format)
  File "/data/omicscore/Easterhoff-Easterhoff-20190501/scripts/conda/envs/py36/lib/python3.6/site-packages/pyir/factory.py", line 159, in split_input_file
    Bio.SeqIO.write(seq, current_pieces[proc_index], 'fasta')
  File "/data/omicscore/Easterhoff-Easterhoff-20190501/scripts/conda/envs/py36/lib/python3.6/site-packages/Bio/SeqIO/__init__.py", line 529, in write
    fp.write(format_function(record))
OSError: [Errno 28] No space left on device
```

Thanks,
Jen

**Comment by reccej** [comment]
Hey Jen,

Thanks for bringing this issue up! Its something we've been running into when processing huge datasets. The most recent update of PyIR includes a "--tmpdir" flag which allows you to set which directory PyIR creates the temporary files in if you would like for it to not default to the TMPDIR value (which is the default of python's tempfile.TemporaryFile method which we've been using). Hopefully this solves any issues you or anyone else were running into
